# Generated by Django 6.1.1 on 2026-09-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.URLField(blank=True),
        ),
    ]
