# Generated by Django 6.1.1 on 2026-09-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('date', models.DateField()),
                ('tipo', models.CharField(choices=[('HAL', 'Halter'), ('ANI', 'Anilha'), ('BAR', 'Barra'), ('KET', 'Kettlebell'), ('CAN', 'Caneleira')], default='HAL', max_length=3)),
            ],
        ),
    ]
